### PR TITLE
#782 - Limited Name to 255 characters

### PR DESCRIPTION
**Pull request by KZavorotna**
Is required for https://github.com/withthegrid/platform-client/pull/924

### CODE REVIEW

**Review by srieding — COMMENTED** [review]
I think we should update the schema in user.ts too

**Comment by everhardt** [comment]
@srieding could you please take over this PR from Kateryna? I think she's busy with other stuff ;). (If not, Kateryna, feel free to let us know and pick it up yourself).

reminder to self: this one also blocks https://github.com/withthegrid/platform-client/pull/925 and related PRs

**Comment by KZavorotna** [comment]
@everhardt I'll take a look at it today

**Comment by KZavorotna** [comment]
@srieding I updated both places with John and Jane Doe
Let me know if I missed smth

**Review by srieding — APPROVED** [review]

**Review by everhardt — APPROVED** [review]
Merci!

**Pull request merged**
